# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deployment
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.OCI_HOST}}
          username: ${{secrets.OCI_USER}}
          key: ${{secrets.OCI_SECRET}}
          source: "./dist/*"
          target: "/usr/local/nginx/html/test"
