# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "master"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          npm run build
          ls

      # - name: Create Sentry release
      #   uses: getsentry/action-release@v1.2.1
      #   env:
      #     SENTRY_AUTH_TOKEN: 4e1ecee376434c46a1e55ab7290d2992da6dfc11ebbf417ea6991bf320bfc703
      #     SENTRY_ORG: shenghongyan-org
      #     SENTRY_PROJECT: about-lifte
      #   with:
      #     sourcemaps: "./dist"

      - name: Install Sentry CLI
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          export VERSION=$(echo `sentry-cli releases propose-version`)
          echo $VERSION
          sentry-cli releases new $VERSION
          sentry-cli releases files $VERSION upload-sourcemaps ./dist/* --url-prefix='http://http://blog.yanshenghong.com/'
          find ./dist -name "*.map" -type f -print -exec rm -rf {} \;
          sentry-cli releases finalize $VERSION


      - name: Deployment
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.OCI_HOST}}
          username: ${{secrets.OCI_USER}}
          key: ${{secrets.OCI_SECRET}}
          source: "./dist/*"
          target: "/usr/local/nginx/html/AboutLife"
